# Generated by Django 5.2.17 on 2026-08-29 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='road_damage/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='road_damage/results/')),
                ('damage_type', models.CharField(blank=True, choices=[('Pothole', 'Pothole'), ('Crack', 'Crack'), ('Surface Damage', 'Surface Damage'), ('Broken Road', 'Broken Road'), ('No Damage', 'No Damage')], max_length=50)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('damage_area_percent', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Reported', 'Reported'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Assigned', 'Assigned'), ('Under Repair', 'Under Repair'), ('Completed', 'Completed')], default='Reported', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_damages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
    ]
