# Generated by Django 5.2.17 on 2026-08-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_roaddamage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='usertype',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
