# Generated by Django 5.2.17 on 2026-08-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roaddamage',
            name='damage_type',
            field=models.CharField(blank=True, choices=[('crack', 'Crack'), ('damage', 'Damage'), ('pothole', 'Pothole'), ('pothole_water', 'Pothole Water'), ('pothole_water_m', 'Pothole Water M'), ('no_damage', 'No Damage')], max_length=50),
        ),
    ]
